Opcodes = {
        "0x0" : {"0x0" : "l.j"},
        "0x1" : {"0x0" : "l.jal"},
        "0x3" : {"0x0" : "l.bnf"},
        "0x4" : {"0x0" : "l.bf"},
        "0x5" : {"0x0" : "l.nop"},
        "0x6" : {"0x0" : "l.movhi", 
                 "0x1" : "l.macrc"},
        "0x8" : {"0x0" : "l.sys", 
                 "0x8" : "l.trap", 
                 "0x10" : "l.msync", 
                 "0x14" : "l.psync", 
                 "0x18" : "l.csync"},
        "0x9" : {"0x0" : "l.rfe"},
        "0xa" : {"0x1" : {"0x10" : "lv.all_eq.b",
                          "0x11" : "lv.all_eq.h",
                          "0x12" : "lv.all_ge.b",
                          "0x13" : "lv.all_ge.h",
                          "0x14" : "lv.all_gt.b",
                          "0x15" : "lv.all_gt.h",
                          "0x16" : "lv.all_le.b",
                          "0x17" : "lv.all_le.h",
                          "0x18" : "lv.all_lt.b",
                          "0x19" : "lv.all_lt.h",
                          "0x1a" : "lv.all_ne.b",
                          "0x1b" : "lv.all_ne.h"},
                 "0x2" : {"0x20" : "lv.any_eq.b",
                          "0x21" : "lv.any_eq.h",
                          "0x22" : "lv.any_ge.b",
                          "0x23" : "lv.any_ge.h",
                          "0x24" : "lv.any_gt.b",
                          "0x25" : "lv.any_gt.h",
                          "0x26" : "lv.any_le.b",
                          "0x27" : "lv.any_le.h",
                          "0x28" : "lv.any_lt.b",
                          "0x29" : "lv.any_lt.h",
                          "0x2a" : "lv.any_ne.b",
                          "0x2b" : "lv.any_ne.h"},
                 "0x3" : {"0x30" : "lv.add.b",
                          "0x31" : "lv.add.h", 
                          "0x32" : "lv.adds.b",
                          "0x33" : "lv.adds.h",
                          "0x34" : "lv.addu.b",
                          "0x35" : "lv.addu.h",
                          "0x36" : "lv.addus.b",
                          "0x37" : "lv.addus.h",
                          "0x38" : "lv.and",
                          "0x39" : "lv.avg.b",
                          "0x3a" : "lv.avg.h"},
                 "0x4" : {"0x40" : "lv.cmp_eq.b",
                          "0x41" : "lv.cmp_eq.h",
                          "0x42" : "lv.cmp_ge.b",
                          "0x43" : "lv.cmp_ge.h",
                          "0x44" : "lv.cmp_gt.b",
                          "0x45" : "lv.cmp_gt.h",
                          "0x46" : "lv.cmp_le.b",
                          "0x47" : "lv.cmp_le.h",
                          "0x48" : "lv.cmp_lt.b",
                          "0x49" : "lv.cmp_lt.h",
                          "0x4a" : "lv.cmp_ne.b",
                          "0x4b" : "lv.cmp_ne.h"},
                 "0x5" : {"0x54" : "lv.madds.h",
                          "0x55" : "lv.max.b",
                          "0x56" : "lv.max.h",
                          "0x57" : "lv.merge.b",
                          "0x58" : "lv.merge.h",
                          "0x59" : "lv.min.b",
                          "0x5a" : "lv.min.h",
                          "0x5b" : "lv.msubs.h",
                          "0x5c" : "lv.muls.h",
                          "0x5d" : "lv.nand",
                          "0x5e" : "lv.nor",
                          "0x5f" : "lv.or"},
                 "0x6" : {"0x60" : "lv.pack.b",
                          "0x61" : "lv.pack.h",
                          "0x62" : "lv.packs.b",
                          "0x63" : "lv.packs.h",
                          "0x64" : "lv.packus.b",
                          "0x65" : "lv.packus.h",
                          "0x66" : "lv.perm.n",
                          "0x67" : "lv.rl.b",
                          "0x68" : "lv.rl.h",
                          "0x69" : "lv.sll.b",
                          "0x6a" : "lv.sll.h",
                          "0x6b" : "lv.sll",
                          "0x6c" : "lv.srl.b",
                          "0x6d" : "lv.srl.h",
                          "0x6e" : "lv.sra.b",
                          "0x6f" : "lv.sra.h"},
                 "0x7" : {"0x70" : "lv.srl",
                          "0x71" : "lv.sub.b",
                          "0x72" : "lv.sub.h",
                          "0x73" : "lv.subs.b",
                          "0x74" : "lv.subs.h",
                          "0x75" : "lv.subu.b",
                          "0x76" : "lv.subu.h",
                          "0x77" : "lv.subus.b",
                          "0x78" : "lv.subus.h",
                          "0x79" : "lv.unpack.b",
                          "0x7a" : "lv.unpack.h",
                          "0x7b" : "lv.xor"},
                 "0xc" : "lv.cust1",
                 "0xd" : "lv.cust2",
                 "0xe" : "lv.cust3",
                 "0xf" : "lv.cust4"},
        "0x11" : {"0x0" : "l.jr"},
        "0x12" : {"0x0" : "l.jalr"},
        "0x13" : {"0x0" : "l.maci"},
        "0x1b" : {"0x0" : "l.lwa"},
        "0x1c" : {"0x0" : "l.cust1"},
        "0x1d" : {"0x0" : "l.cust2"},
        "0x1e" : {"0x0" : "l.cust3"},
        "0x1f" : {"0x0" : "l.cust4"},
        "0x20" : {"0x0" : "l.ld"},
        "0x21" : {"0x0" : "l.lwz"},
        "0x22" : {"0x0" : "l.lws"},
        "0x23" : {"0x0" : "l.lbz"},
        "0x24" : {"0x0" : "l.lbs"},
        "0x25" : {"0x0" : "l.lhz"},
        "0x26" : {"0x0" : "l.lhs"},
        "0x27" : {"0x0" : "l.addi"},
        "0x28" : {"0x0" : "l.addic"},
        "0x29" : {"0x0" : "l.andi"},
        "0x2a" : {"0x0" : "l.ori"},
        "0x2b" : {"0x0" : "l.xori"},
        "0x2c" : {"0x0" : "l.muli"},
        "0x2d" : {"0x0" : "l.mfspr"},
        "0x2e" : {"0x0" : "l.slli",
                  "0x1" : "l.srli",
                  "0x2" : "l.srai",
                  "0x3" : "l.rori"},
        "0x2f" : {"0x0" : "l.sfeqi",
                  "0x1" : "l.sfnei",
                  "0x2" : "l.sfgtui",
                  "0x3" : "l.sfgeui",
                  "0x4" : "l.sfgtui",
                  "0x5" : "l.sfleui",
                  "0xa" : "l.sfgtsi",
                  "0xb" : "l.sfgesi",
                  "0xc" : "l.sfltsi",
                  "0xd" : "l.sflesi"},
        "0x30" : {"0x0" : "l.mtspr"},
        "0x31" : {"0x1" : "l.mac",
                  "0x2" : "l.msb"},
        "0x32" : {"0x0" : {"0x0" : "lf.add.s",
                           "0x1" : "lf.sub.s",
                           "0x2" : "lf.mul.s",
                           "0x3" : "lf.div.s",
                           "0x4" : "lf.itof.s",
                           "0x5" : "lf.ftoi.s",
                           "0x6" : "lf.rem.s",
                           "0x7" : "lf.madd.s",
                           "0x8" : "lf.sfeq.s",
                           "0x9" : "lf.sfne.s",
                           "0xa" : "lf.sfgt.s",
                           "0xb" : "lf.sfge.s",
                           "0xc" : "lf.sflt.s",
                           "0xd" : "lf.sfle.s"},
                  "0xd" : "lf.cust1.s",
                  "0x1" : {"0x10" : "lf.add.d",
                           "0x11" : "lf.sub.d",
                           "0x12" : "lf.mul.d",
                           "0x13" : "lf.div.d",
                           "0x14" : "lf.itof.d",
                           "0x15" : "lf.ftoi.d",
                           "0x16" : "lf.rem.d",
                           "0x17" : "lf.madd.d",
                           "0x18" : "lf.sfeq.d",
                           "0x19" : "lf.sfne.d",
                           "0x1a" : "lf.sfgt.d",
                           "0x1b" : "lf.sfge.d",
                           "0x1c" : "lf.sflt.d",
                           "0x1d" : "lf.sfle.d"},
                  "0xe" : "lf.cust1.d"},
        "0x33" : {"0x0" : "l.swa"},
        "0x34" : {"0x0" : "l.sd"},
        "0x35" : {"0x0" : "l.sw"},
        "0x36" : {"0x0" : "l.sb"},
        "0x37" : {"0x0" : "l.sh"},
        "0x38" : {"0x0" : {"0x0" : "l.add",
                           "0x1" : "l.addc",
                           "0x2" : "l.sub",
                           "0x3" : "l.and",
                           "0x4" : "l.or",
                           "0x5" : "l.xor",
                           "0x8" : {"0x0" : "l.sll",
                                    "0x1" : "l.srl",
                                    "0x2" : "l.sra",
                                    "0x3" : "l.ror"},
                           "0xc" : {"0x0" : "l.exths",
                                    "0x1" : "l.extbs",
                                    "0x2" : "l.exthz",
                                    "0x3" : "l.extbz"},
                           "0xd" : {"0x0" : "l.extws",
                                    "0x1" : "l.extwz"},
                           "0xe" : "l.cmov",
                           "0xf" : "l.ff1"},
                  "0x1" : {"0xf" : "l.fl1"},
                  "0x3" : {"0x6" : "l.mul",
                           "0x9" : "l.div",
                           "0xa" : "l.divu",
                           "0xb" : "l.mulu"}},
        "0x39" : {"0x0" : "l.sfeq",
                  "0x1" : "l.sfne",
                  "0x2" : "l.sfgtu",
                  "0x3" : "l.sfgeu",
                  "0x4" : "l.sfltu",
                  "0x5" : "l.sfleu",
                  "0xa" : "l.sfgts",
                  "0xb" : "l.sfges",
                  "0xc" : "l.sflts",
                  "0xd" : "l.sfles"},
        "0x3c" : {"0x0" : "l.cust5"},
        "0x3d" : {"0x0" : "l.cust6"},
        "0x3e" : {"0x0" : "l.cust7"},
        "0x3f" : {"0x0" : "l.cust8"}
} 
