Operands = {
        "l.j" : ["N"],
        "l.jal" : ["N"],
        "l.bnf" : ["N"],
        "l.bf" : ["N"],
        "l.nop" : ["K"],
        "l.movhi" : ["rD", "K"],
        "l.macrc" : ["rD"],
        "l.sys" : ["K"],
        "l.trap" : ["K"],
        "l.msync" : [],
        "l.psync" : [],
        "l.csync" : [],
        "l.rfe" : [],
        "lv.all_eq.b" : ["rD", "rA", "rB"],
        "lv.all_eq.h" : ["rD", "rA", "rB"],
        "lv.all_ge.b" : ["rD", "rA", "rB"],
        "lv.all_ge.h" : ["rD", "rA", "rB"],
        "lv.all_gt.b" : ["rD", "rA", "rB"],
        "lv.all_gt.h" : ["rD", "rA", "rB"],
        "lv.all_le.b" : ["rD", "rA", "rB"],
        "lv.all_le.h" : ["rD", "rA", "rB"],
        "lv.all_lt.b" : ["rD", "rA", "rB"],
        "lv.all_lt.h" : ["rD", "rA", "rB"],
        "lv.all_ne.b" : ["rD", "rA", "rB"],
        "lv.all_ne.h" : ["rD", "rA", "rB"],
        "lv.any_eq.b" : ["rD", "rA", "rB"],
        "lv.any_eq.h" : ["rD", "rA", "rB"],
        "lv.any_ge.b" : ["rD", "rA", "rB"],
        "lv.any_ge.h" : ["rD", "rA", "rB"],
        "lv.any_gt.b" : ["rD", "rA", "rB"],
        "lv.any_gt.h" : ["rD", "rA", "rB"],
        "lv.any_le.b" : ["rD", "rA", "rB"],
        "lv.any_le.h" : ["rD", "rA", "rB"],
        "lv.any_lt.b" : ["rD", "rA", "rB"],
        "lv.any_lt.h" : ["rD", "rA", "rB"],
        "lv.any_ne.b" : ["rD", "rA", "rB"],
        "lv.any_ne.h" : ["rD", "rA", "rB"],
        "lv.add.b" : ["rD", "rA", "rB"],
        "lv.add.h" : ["rD", "rA", "rB"],
        "lv.adds.b" : ["rD", "rA", "rB"],
        "lv.adds.h" : ["rD", "rA", "rB"],
        "lv.addu.b" : ["rD", "rA", "rB"],
        "lv.addu.h" : ["rD", "rA", "rB"],
        "lv.addus.b" : ["rD", "rA", "rB"],
        "lv.addus.h" : ["rD", "rA", "rB"],
        "lv.and" : ["rD", "rA", "rB"],
        "lv.avg.b" : ["rD", "rA", "rB"],
        "lv.avg.h" : ["rD", "rA", "rB"],
        "lv.cmp_eq.b" : ["rD", "rA", "rB"],
        "lv.cmp_eq.h" : ["rD", "rA", "rB"],
        "lv.cmp_ge.b" : ["rD", "rA", "rB"],
        "lv.cmp_ge.h" : ["rD", "rA", "rB"],
        "lv.cmp_gt.b" : ["rD", "rA", "rB"],
        "lv.cmp_gt.h" : ["rD", "rA", "rB"],
        "lv.cmp_le.b" : ["rD", "rA", "rB"],
        "lv.cmp_le.h" : ["rD", "rA", "rB"],
        "lv.cmp_lt.b" : ["rD", "rA", "rB"],
        "lv.cmp_lt.h" : ["rD", "rA", "rB"],
        "lv.cmp_ne.b" : ["rD", "rA", "rB"],
        "lv.cmp_ne.h" : ["rD", "rA", "rB"],
        "lv.madds.h" : ["rD", "rA", "rB"],
        "lv.max.b" : ["rD", "rA", "rB"],
        "lv.max.h" : ["rD", "rA", "rB"],
        "lv.merge.b" : ["rD", "rA", "rB"], 
        "lv.merge.h" : ["rD", "rA", "rB"],
        "lv.min.b" : ["rD", "rA", "rB"],
        "lv.min.h" : ["rD", "rA", "rB"],
        "lv.msubs.h" : ["rD", "rA", "rB"],
        "lv.muls.h" : ["rD", "rA", "rB"],
        "lv.nand" : ["rD", "rA", "rB"],
        "lv.nor" : ["rD", "rA", "rB"],
        "lv.or" : ["rD", "rA", "rB"],
        "lv.pack.b" : ["rD", "rA", "rB"],
        "lv.pack.h" : ["rD", "rA", "rB"],
        "lv.packs.b" : ["rD", "rA", "rB"],
        "lv.packs.h" : ["rD", "rA", "rB"],
        "lv.packus.b" : ["rD", "rA", "rB"],
        "lv.packus.h" : ["rD", "rA", "rB"],
        "lv.perm.n" : ["rD", "rA", "rB"],
        "lv.rl.b" : ["rD", "rA", "rB"],
        "lv.rl.h" : ["rD", "rA", "rB"],
        "lv.sll.b" : ["rD", "rA", "rB"],
        "lv.sll.h" : ["rD", "rA", "rB"],
        "lv.sll" : ["rD", "rA", "rB"],
        "lv.srl.b" : ["rD", "rA", "rB"],
        "lv.srl.h" : ["rD", "rA", "rB"],
        "lv.sra.b" : ["rD", "rA", "rB"],
        "lv.sra.h" : ["rD", "rA", "rB"],
        "lv.srl" : ["rD", "rA", "rB"],
        "lv.sub.b" : ["rD", "rA", "rB"],
        "lv.sub.h" : ["rD", "rA", "rB"],
        "lv.subs.b" : ["rD", "rA", "rB"],
        "lv.subs.h" : ["rD", "rA", "rB"],
        "lv.subu.b" : ["rD", "rA", "rB"],
        "lv.subu.h" : ["rD", "rA", "rB"],
        "lv.subus.b" : ["rD", "rA", "rB"],
        "lv.subus.h" : ["rD", "rA", "rB"],
        "lv.unpack.b" : ["rD", "rA", "rB"],
        "lv.unpack.h" : ["rD", "rA", "rB"],
        "lv.xor" : ["rD", "rA", "rB"],
        "lv.cust1" : [],
        "lv.cust2" : [],
        "lv.cust3" : [],
        "lv.cust4" : [],
        "l.jr" : ["rB"],
        "l.jalr" : ["rB"],
        "l.maci" : ["rA", "I"],
        "l.lwa" : ["rD", "I", "(", "rA", ")"],
        "l.cust1" : [],
        "l.cust2" : [],
        "l.cust3" : [],
        "l.cust4" : [],
        "l.ld" : ["rD", "I", "(", "rA", ")"],
        "l.lwz" : ["rD", "I", "(", "rA", ")"],
        "l.lws" : ["rD", "I", "(", "rA", ")"],
        "l.lbz" : ["rD", "I", "(", "rA", ")"],
        "l.lbs" : ["rD", "I", "(", "rA", ")"],
        "l.lhz" : ["rD", "I", "(", "rA", ")"],
        "l.lhs" : ["rD", "I", "(", "rA", ")"],
        "l.addi" : ["rD", "rA", "I"],
        "l.addic" : ["rD", "rA", "I"],
        "l.andi" : ["rD", "rA", "K"],
        "l.ori" : ["rD", "rA", "K"],
        "l.xori" : ["rD", "rA", "I"],
        "l.muli" : ["rD", "rA", "I"],
        "l.mfspr" : ["rD", "rA", "K"],
        "l.slli" : ["rD", "rA", "L"],
        "l.srli" : ["rD", "rA", "L"],
        "l.srai" : ["rD", "rA", "L"],
        "l.rori" : ["rD", "rA", "L"],
        "l.sfeqi" : ["rA", "I"],
        "l.sfnei" : ["rA", "I"],
        "l.sfgtui" : ["rA", "I"],
        "l.sfgeui" : ["rA", "I"],
        "l.sfltui" : ["rA", "I"],
        "l.sfleui" : ["rA", "I"],
        "l.sfgtsi" : ["rA", "I"],
        "l.sfgesi" : ["rA", "I"],
        "l.sfltsi" : ["rA", "I"],
        "l.sflesi" : ["rA", "I"],
        "l.mtspr" : ["rA", "rB", "K"],
        "l.mac" : ["rA", "rB"],
        "l.msb" : ["rA", "rB"],
        "lf.add.s" : ["rD", "rA", "rB"],
        "lf.sub.s" : ["rD", "rA", "rB"],
        "lf.mul.s" : ["rD", "rA", "rB"],
        "lf.div.s" : ["rD", "rA", "rB"],
        "lf.itof.s" : ["rD", "rA"],
        "lf.ftoi.s" : ["rD", "rA"],
        "lf.rem.s" : ["rD", "rA", "rB"],
        "lf.madd.s" : ["rD", "rA", "rB"],
        "lf.sfeq.s" : ["rA", "rB"],
        "lf.sfne.s" : ["rA", "rB"],
        "lf.sfgt.s" : ["rA", "rB"],
        "lf.sfge.s" : ["rA", "rB"], 
        "lf.sflt.s" : ["rA", "rB"],
        "lf.sfle.s" : ["rA", "rB"],
        "lf.cust1.s" : ["rA", "rB"],
        "lf.add.d" : ["rD", "rA", "rB"],
        "lf.sub.d" : ["rD", "rA", "rB"],
        "lf.mul.d" : ["rD", "rA", "rB"],
        "lf.div.d" : ["rD", "rA", "rB"],
        "lf.itof.d" : ["rD", "rA"],
        "lf.ftoi.d" : ["rD", "rA"],
        "lf.rem.d" : ["rD", "rA", "rB"],
        "lf.madd.d" : ["rD", "rA", "rB"],
        "lf.sfeq.d" : ["rA", "rB"], 
        "lf.sfne.d" : ["rA", "rB"],
        "lf.sfgt.d" : ["rA", "rB"],
        "lf.sfge.d" : ["rA", "rB"],
        "lf.sflt.d" : ["rA", "rB"],
        "lf.sfle.d" : ["rA", "rB"],
        "lf.cust1.d" : ["rA", "rB"],
        "l.swa" : ["I", "(", "rA", ")", "rB"],
        "l.sd" : ["I", "(", "rA", ")", "rB"],
        "l.sw" : ["I", "(", "rA", ")", "rB"],
        "l.sb" : ["I", "(", "rA", ")", "rB"],
        "l.sh" : ["I", "(", "rA", ")", "rB"],
        "l.add" : ["rD", "rA", "rB"],
        "l.addc" : ["rD", "rA", "rB"],
        "l.sub" : ["rD", "rA", "rB"],
        "l.and" : ["rD", "rA", "rB"],
        "l.or" : ["rD", "rA", "rB"],
        "l.xor" : ["rD", "rA", "rB"],
        "l.mul" : ["rD", "rA", "rB"],
        "l.sll" : ["rD", "rA", "rB"],
        "l.srl" : ["rD", "rA", "rB"],
        "l.sra" : ["rD", "rA", "rB"],
        "l.ror" : ["rD", "rA", "rB"],
        "l.div" : ["rD", "rA", "rB"],
        "l.divu" : ["rD", "rA", "rB"],
        "l.mulu" : ["rD", "rA", "rB"],
        "l.extbs" : ["rD", "rA"],
        "l.exths" : ["rD", "rA"],
        "l.extws" : ["rD", "rA"],
        "l.extbz" : ["rD", "rA"],
        "l.exthz" : ["rD", "rA"],
        "l.extwz" : ["rD", "rA"],
        "l.cmov" : ["rD", "rA", "rB"],
        "l.ff1" : ["rD", "rA"],
        "l.fl1" : ["rD", "rA"],
        "l.sfeq" : ["rA", "rB"],
        "l.sfne" : ["rA", "rB"],
        "l.sfgtu" : ["rA", "rB"],
        "l.sfgeu" : ["rA", "rB"],
        "l.sfltu" : ["rA", "rB"],
        "l.sfleu" : ["rA", "rB"],
        "l.sfgts" : ["rA", "rB"],
        "l.sfges" : ["rA", "rB"],
        "l.sflts" : ["rA", "rB"],
        "l.sfles" : ["rA", "rB"],
        "l.cust5" : [],
        "l.cust6" : [],
        "l.cust7" : [],
        "l.cust8" : []
}
